services:
  # sudo docker exec -it bot-redis redis-cli
  redis:
    image: redis:latest
    container_name: bot-redis
    ports:
      - "6389:6379"
    networks:
      - bot-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: bot-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=bot-cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    networks:
      - bot-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  postgres:
    image: postgres:latest
    container_name: bot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-db
    ports:
      - "5482:5432"
    networks:
      - bot-network
    volumes:
      - postgresdata:/var/lib/postgresql/data

networks:
  bot-network:
    
volumes:
  esdata:
  postgresdata: